# Dependencies
markdown:         kramdown #redcarpet
highlighter:	  rouge #pygments

# Permalinks
permalink:        pretty

# Setup
title:            jereliu
tagline:          'Jeremiah Zhe Liu'
description:      'Machine Learning Researcher <br> Practicing Probabilists <br> Open Source Monkey'
url:              http://jereliu.github.io

author:
  name:           'Jeremiah Zhe Liu'
  url:            http://jereliu.github.io

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           
