name: "Will Townes"
description: "technical blog"
url: "http://localhost:4000"
paginate: 10
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
highlighter: pygments