name: "Jeremiah Zhe Liu"
description: "technical blog"
url: "http://0.0.0.0:4444/"
paginate: 10
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
highlighter: pygments