name: "Jeremiah Zhe Liu"
description: "technical blog"
url: "http://jereliu.github.io"
paginate: 10
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
highlighter: pygments